### ISSUE TITLE
Conflict with Arduino-BLE-MIDI libray

### ISSUE THREAD

**Issue by alf45tar** [improv-wifi/sdk-cpp#4]
Other libraries are using SERVICE_UUID symbol too. I think it is better to differentiate a little bit the name.

https://github.com/improv-wifi/sdk-cpp/blob/e8d51778936868c0f137a204147f40d98805569b/src/improv.h#L13

https://github.com/lathoub/Arduino-BLE-MIDI/blob/4724511fa88b08144b4485328d6d5d650926e788/src/BLEMIDI_Defs.h#L9

**Comment by jesserockz** [comment]
Well the const here is namespaced, perhaps the other library should namespace its symbols too?
